### ISSUE TITLE
nix flakes

### ISSUE THREAD

**Issue by shish** [shish/rosettaboy#111]
Nix flakes appear to have a bunch of benefits over the current `shell.nix` approach, but they also seem more complicated to set up and I haven't got my head around them yet...

I think in my ideal world:
- `nix develop` runs a shell with all the development tools necessary to build things
  - if run in the root, it installs all deps for all langauges; if run inside a language folder, it only installs what's needed for that langauge
  - From within the shell launched from the root folder, `./utils/bench.py --default --frames 10 --threads 4` should report everything passing
- `nix build` builds binaries for the current language / all languages
  - to avoid naming conflicts, maybe the output binaries should be named `bin/rosettaboy-<language>-<variant>` instead of `<language>/rosettaboy-<variant>`?
- it's possible to install by URL?
  - Something like `nix shell github:shish/rosettaboy` will build and install all the versions?
  - Does nix have a syntax for subfolders, so people can `nix shell` a specific language version without needing to pull in hundreds of megs of dev tools for all languages?

**Comment by jbboehr** [comment]
The flake way appears to be to expose them all as attributes in the root flake, so:

```shell
# from flake.nix devShells."<system>".${attr}
nix develop .
nix develop .#cpp
# could also probably be nix develop .#cpp.lto
nix develop .#cpp-lto
nix develop .#php
# etc

# from flake.nix packages."<system>".${attr}
nix build . 
nix build .#cpp
nix build .#cpp-lto
nix build .#php
# etc

# from flake.nix apps."<system>".${attr}
nix run . 
nix run .#cpp
nix run .#cpp-lto
nix run .#php
# etc

# Or from a URL:
nix run github.com:shish/rosettaboy#php
```

Although there isn't currently an implementation for `build` or `run`, so that would have to be implemented if you wanted those to work.

Although there's probably better examples, I flake-ified [this](https://github.com/jbboehr/handlebars.c/blob/master/flake.nix) recently as an example.

See: https://nixos.wiki/wiki/Flakes#Output_schema

**Comment by jbboehr** [comment]
In general, you can actually re-use most already-written nix scripts in either direction, as long as they are pure.

From flake-style to old-style: just call e.g. `pkgs.callPackage ./shell.nix { inherit pkgs; }` inside the flake [[0]](https://github.com/jbboehr/handlebars.c/blob/master/flake.nix#L49)

From old-style to flake-style: https://github.com/edolstra/flake-compat

**Comment by jbboehr** [comment]
I think I would recommend starting by adding old-style build derivations for each language in e.g. `cpp/default.nix` and/or `cpp/derivation.nix` and making sure they are working, and then later importing them into a flake.

You also get most of a devShell for free when you implement the build derivation.

**Comment by rrbutani** [comment]
I mentioned [in #57](https://github.com/shish/rosettaboy/issues/57#issuecomment-1332564900) that I started putting together [a flake](https://github.com/rrbutani/rosettaboy/commit/ff7a671848369b35cc372cda016aafe9f5ce3e6e#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0) for rosettaboy way back when. It's definitely fallen out of date by now but hopefully it's still a useful starting point.

In addition to what you described in the OP:
   - `devShells.<language>` to a dev-shell for a sub-folder with `nix develop .#<language>`, `devShells.default`/`nix develop` for a shell with all the deps
   - `packages.<language>` for `nix build`
   - `apps.<language>` for `nix run`

I was also aiming to:
  - expose the tests and lint checks under `checks.` (though I only got around to [doing `opus5`](https://github.com/rrbutani/rosettaboy/commit/ff7a671848369b35cc372cda016aafe9f5ce3e6e#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R244-R248))
  - and to expose [`apps.<language>-bench` targets](https://github.com/rrbutani/rosettaboy/commit/ff7a671848369b35cc372cda016aafe9f5ce3e6e#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R231-R239) (i.e. `nix run .#cpp-bench`)

---

> * `nix develop` runs a shell with all the development tools necessary to build things
>   * if run in the root, it installs all deps for all langauges; if run inside a language folder, it only installs what's needed for that langauge

>   * Does nix have a syntax for subfolders, so people can `nix shell` a specific language version without needing to pull in hundreds of megs of dev tools for all languages?

@jbboehr is correct; the idiomatic way to expose separate devShells/packages/etc. is with `devShell.<language>` outputs in the flake. `nix` commands within a flake aren't really sensitive to the subdirectory within a flake that they're run in so you'd need to, for example, run `nix develop .#cpp` instead of just running `nix develop` in the `cpp` subdir.

I believe it's possible to get `nix develop` in language subdirs to do with you're describing using sub-flakes but I think that going that route is more trouble than it's worth (requires a fair bit of duplication; a separate flake + lock file per language in addition to a top-level one).

Using [`direnv`](https://github.com/nix-community/nix-direnv) with `use flake .#<language>` (or `use flake .#$(basename .)` if you want since it ultimately is just bash) in an `.envrc` in each language directory gets you pretty close to what you're describing though (on `cd` into each language directory your shell is updated with the state from `nix develop .#<language>`).

>   * to avoid naming conflicts, maybe the output binaries should be named `bin/rosettaboy-<language>-<variant>` instead of `<language>/rosettaboy-<variant>`?

> * it's possible to install by URL?
>   * Something like `nix shell github:shish/rosettaboy` will build and install all the versions?

`nix run .#<language>` would let you run without "installing" the rosettaboy binaries; I think [`nix profile install`](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-install.html) would be more akin to installing.

For the former (`nix run`) there's no issue with the binaries all being named `rosettaboy` but in the latter case you're totally right: the binary names would clash (and `nix profile install` would complain about this assuming all the packages have the same [priority](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-install.html#options)).

---

I think the bulk of the work here will be getting each language's impl to build in the sandbox (and then to run in the sandbox if you want to have `checks.`).

A good first step is probably to add a flake with just `devShells` for each language (where each output just imports the corresponding `shell.nix`); something like this: https://github.com/rrbutani/rosettaboy/tree/nix-flake-devShells

https://github.com/shish/rosettaboy/blob/453043bcb7e4e3cd374f3545d6cdef5ccaeb8a91/flake.nix#L8-L39

If the above looks okay, I can open a PR.

**Comment by shish** [comment]
> run nix develop .#cpp instead of just running nix develop in the cpp subdir.

This seems fine to me - I'm happy to adjust myself to do things the idiomatic way, rather than trying to force nix to conform to my idea of how I'd do it if I were building from scratch :)

**Comment by jbboehr** [comment]
I've been looking into writing derivations for some of the other languages and a lot of the nix language tooling is moving to flakes, so I think it would be good to get a basic flake up and running. I can make it work without flakes, but it's [ugly](https://github.com/jbboehr/php-handlebars/blob/c270cba54ec0425865930e4e414e63ae37e83027/default.nix#L8-L49).

@rrbutani's `nix-flake-devShells` branch looks like a solid base to me, although, and I know the existing code does this, I would avoid using iteration for the language packages as, assuming you want to put language-specific nix files in the language folders, it'll probably be desirable to pass a subset of inputs from the flake into each one, e.g.

```nix
rec {
  packages = {
    go = pkgs.callPackage ./go/derivation.nix { inherit gomod2nix; };
    rust = pkgs.callPackage ./rust/derivation.nix { inherit naersk; };
    rust-debug = pkgs.callPackage ./rust/derivation.nix { inherit naersk; debugSupport = true; };
    rust-lto = pkgs.callPackage ./rust/derivation.nix { inherit naersk; ltoSupport = true; };
  };
}
```

Some of the ones I looked into briefly so far:

Rust via https://github.com/nix-community/naersk
Go via https://github.com/nix-community/gomod2nix
Python via https://github.com/nix-community/poetry2nix
